set(PLATFORM_REQUIRED_DEPS LibAndroidJNI OpenGLES EGL LibZip)
set(PLATFORM_OPTIONAL_DEPS_EXCLUDE CEC)
set(APP_RENDER_SYSTEM gles)
list(APPEND PLATFORM_OPTIONAL_DEPS LibDovi)

# Store SDK compile version
<<<<<<< HEAD
set(TARGET_SDK 31)
=======
set(TARGET_SDK 34)
>>>>>>> c48c9e6fab75a437bbdbbdc330bd25d640d195f8
# Minimum supported SDK version
set(TARGET_MINSDK 24)

set(${CORE_PLATFORM_NAME_LC}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
